version: "3"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "authorization-server"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
